export default {
  REQUEST_FIELD_CONFIG: 'REQUEST_FIELD_CONFIG',
  RECEIVE_FIELD_CONFIG: 'RECEIVE_FIELD_CONFIG',
  FETCH_FIELD_CONFIG_FAIL: 'FETCH_FIELD_CONFIG_FAIL',

  REQUEST_CHANNELS: 'REQUEST_CHANNELS',
  RECEIVE_CHANNELS: 'RECEIVE_CHANNELS',
  FETCH_CHANNELS_FAIL: 'FETCH_CHANNELS_FAIL',

  CLEAR_REPORT_DATA: 'CLEAR_REPORT_DATA',
  ENABLE_LOADING_MODAL: 'ENABLE_LOADING_MODAL',
  DISABLE_LOADING_MODAL: 'DISABLE_LOADING_MODAL',
};
